### PR TITLE
Gave alternate viewCart solution

### PR DESCRIPTION
**Pull request by pickledyamsman**
This is based more on the examples in the lesson.

@aturkewi

### CODE REVIEW

**Comment by aturkewi** [comment]
Looks good @pickledyamsman can you format this in a way that I can actually merge it in?

**Comment by bhollan** [comment]
Big fan of this idea.  I like the fancy solutions usually, but have an example of "this is how the lesson teaches it" in the solution is a really good idea.

**Comment by aturkewi** [comment]
Excellent, can either of your format this in a way that it's not just an Issue but and actual PR? Or am I missing something and this _should_ be merged in as a comment?

**Comment by bhollan** [comment]
Aren't we conversing inside a PR?  I might be confused.

`https://github.com/learn-co-curriculum/js-basics-online-shopping-lab/pull/38`

**Comment by JessRudder** [comment]
@bhollan, @pickledyamsman I believe @aturkewi is asking for the PR to be rewritten so that the readme contains what should be shown to the student.  Right now, it's commented out code and a note.  It looks more internal facing than external.  If we merged in this PR, that's what would go out to students.

**Comment by aturkewi** [comment]
Thanks for helping make this clearer Jess :)
That's correct, we just want to update the code. I don't want to have _two_ solutions in the same file, one that runs and one that's comments. It feels really confusing and as soon as any change is made the comments will fall out of sync.

**Pull request closed without merging**
